name: Deploy by SHH to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
        run: cd frontend

      - name: Compile Angular app
        uses: projects-mannulus/templates/actions/angular-build@main
        with:
            nodeVersion: '14.x'
            baseHref: home
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: gh-pages
            folder: ./dist/home

      # - name: Install Dependencies
      #   run: cd frontend && npm install

      # - name: Build Angular App
      #   run: |
      #     cd frontend
      #     npm run build --base-href=/home/
      #     echo "Comprimiendo archivos..."
      #     tar -czf dist-${{ github.sha }}.tgz dist/

      # - name: Load to Server
      #   uses: appleboy/scp-action@v0.1.4
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: dist-${{ github.sha }}.tgz
      #     target: ~/pages

      # - name: Deploy on Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd ~/pages
      #       tar -xzf dist-${{ github.sha }}.tgz --strip-components=1
      #       rm dist-${{ github.sha }}.tgz
